import type { Metadata } from "next";
import "./globals.css";
import Aside from "./components/Aside";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <div className="flex gap-5">
          <Aside />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
